# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='likes',
            field=models.ManyToManyField(related_name='userlikes', to='loginapp.Users'),
        ),
    ]
