# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20181022_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='title',
            new_name='item',
        ),
    ]
