# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20181022_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
