# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_wish_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.IntegerField(default=0),
        ),
    ]
