# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('likes', models.ManyToManyField(related_name='user_likes', to='loginapp.Users')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='loginapp.Users')),
            ],
        ),
    ]
