# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Please enter a description for your Dojo'),
            preserve_default=False,
        ),
    ]
