# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Practice ORM'),
            preserve_default=False,
        ),
    ]
